
#Spring security
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-14224985.okta.com/oauth2/default
          
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaay83donpiJQ5DA5d7
            client-secret: HAq5V5dFwdWkvl_VJm_kMkNWYESJtVwX6bLN4eAXFB_Hh913saQdu4oBmcgoKbj3
        provider:
          okta: 
             issuer-uri: https://dev-14224985.okta.com/oauth2/default
          
